### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by robotlolita** [origamitower/origami#2]
A list of things I'm leaving to fix later:

- [ ] Origami needs Logical and Arithmetic precedence, without transient/universal precedence (Fortress-like), currently we just have Binary > Unary
- [ ] Abstract classes
- [ ] Property accesses aren't checked yet (`a.b` succeeds even if `b` doesn't exist)
- [ ] Spread for objects (a tiny bit more complicated because it should preserve structure/not evaluate getters);
- [x] Named parameters (using an object for the last positional argument);
- [ ] Allow dynamic properties in classes (this is tricky because we don't want to run code at module instantiation...)
- [x] Move runtime to a separate library
- [x] Fix whatever weird thing babel plugins are doing
- [ ] Allow users to customize plugins + compile-literal parameters + package default options
- [ ] Extractors don't support spread or named parameters
